create table public.pensamentos (
  id bigint generated by default as identity primary key,
  conteudo text not null,
  autoria text not null,
  modelo text not null default 'modelo1',
  favorito boolean not null default false
);

alter table public.pensamentos enable row level security;

create policy "pensamentos_select_publico" on public.pensamentos for select to anon, authenticated using (true);
create policy "pensamentos_insert_publico" on public.pensamentos for insert to anon, authenticated with check (true);
create policy "pensamentos_update_publico" on public.pensamentos for update to anon, authenticated using (true) with check (true);
create policy "pensamentos_delete_publico" on public.pensamentos for delete to anon, authenticated using (true);

insert into public.pensamentos (id, conteudo, autoria, modelo, favorito) overriding system value values
  (2, 'Na volta a gente compra!', 'Mãe', 'modelo2', false),
  (4, 'Vc faz TI? Conserta meu celular!', 'Grupo da família', 'modelo2', false),
  (5, 'Já tentou reiniciar o roteador?', 'Pessoa da operadora', 'modelo3', false),
  (6, 'Da vida reclama, mas sem ela não vive!', 'Mestre Yoda', 'modelo1', true),
  (7, 'Na minha máquina funciona!', 'Dev', 'modelo3', false),
  (9, 'Esse é de laranja que parece de limão, mas tem gosto de tamarindo!', 'Chaves', 'modelo1', false),
  (13, 'Melhor professor, o fracasso é!', 'Mestre Yoda', 'modelo2', false),
  (14, 'Você não é todo mundo!', 'Mãe', 'modelo2', true),
  (15, 'Foi sem querer querendo!', 'Chaves', 'modelo3', false),
  (16, 'Em casa a gente conversa!', 'Mãe', 'modelo3', false),
  (17, 'Que a força esteja com você!', 'Mestre Yoda', 'modelo1', false),
  (18, 'Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Diuretics paradis num copo é motivis de denguis. Atirei o pau no gatis, per gatis num morreus. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. Sapien in monti palavris qui num significa nadis i pareci latim.', 'Mussum', 'modelo3', false),
  (19, 'Por que a pessoa dev não morre afogada? Porque ela usa ponto flutuante.', 'Grupo da família', 'modelo1', false),
  (20, 'Leva o casaco que vai esfriar!', 'Mãe', 'modelo2', false),
  (21, 'Sou poliglota; falo português, inglês e JavaScript!', 'Dev', 'modelo1', false),
  (22, 'Não faça drama, faça café! :)', 'Dev', 'modelo2', false),
  (23, 'Conserta minha impressora?', 'Grupo da família', 'modelo3', false),
  (24, 'Não fez mais que a sua obrigação!', 'Mãe', 'modelo1', false),
  (25, 'Por que meu código funcionou?', 'Dev ', 'modelo1', false),
  (27, 'Resolver o bug não consegue? Esfriar a cabeça você deve.', 'Mestre Yoda', 'modelo1', false),
  (28, 'Se eu for aí e achar, eu esfrego na sua cara!', 'Mãe', 'modelo3', true),
  (30, 'Parangari', 'Cutirimirruaro', 'modelo3', false);

select setval(pg_get_serial_sequence('public.pensamentos','id'), (select max(id) from public.pensamentos));
